en:
  languageCode: en-us
zh:
  languageCode: zh-Hans
  title: 李嘉渝 | BlackiePiggy
  params:
    description: 李嘉渝的个人主页与经历展示
  menu:
    main:
      - name: 主页
        identifier: 46a9df65
        url: /
        weight: 10
        params:
          hidden: false
      - name: 经历
        identifier: 6334c278
        url: experience/
        weight: 20
        params:
          hidden: false
      - name: 项目
        identifier: menu-mmpvag6r
        url: projects/
        weight: 30
        params:
          hidden: false
      - name: 想法
        identifier: idea
        url: idea/
        weight: 40
        params:
          hidden: false
      - name: 论文
        identifier: f31c7d6c
        url: /#papers
        weight: 50
        params:
          hidden: false
      - name: 动态
        identifier: 7a7afbbd
        url: /#news
        weight: 60
        params:
          hidden: false
      - name: 生活
        identifier: c0853a40
        url: /#talks
        weight: 70
        params:
          hidden: false
