main:
  - name: Bio
    identifier: 46a9df65
    url: /
    weight: 10
    params:
      hidden: false
  - name: Experience
    identifier: 6334c278
    url: experience/
    weight: 20
    params:
      hidden: false
  - name: Project
    identifier: menu-mmpvag6r
    url: projects/
    weight: 30
    params:
      hidden: false
  - name: Idea
    identifier: idea
    url: idea/
    weight: 40
    params:
      hidden: false
  - name: Papers
    identifier: f31c7d6c
    url: /#papers
    weight: 50
    params:
      hidden: false
  - name: News
    identifier: 7a7afbbd
    url: /#news
    weight: 60
    params:
      hidden: false
  - name: Life
    identifier: c0853a40
    url: /#talks
    weight: 70
    params:
      hidden: false
